### ISSUE TITLE
Check status of v4 electronics kit

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#11]
We absolutely must have enough working kits for the number of teams we intend to invite to participate.

We therefore need to know how many kit pieces we have in working order, ideally before we confirm places to teams.

**Comment by PeterJCLaw** [comment]
This depends on getting access to the kits which I assume are stored in Newbury. I'm not sure whether that means that this is dependant on #8 or not.

I think the steps here are:
- find out what testing procedures exist for the kit and, ideally, familiarise ourselves within them (https://bitbucket.org/richardbarlow/sr-hw-prod-coord/wiki/Kit_Collation#markdown-header-test appears to be a good starting point)
- collate the kit we have in storage (https://bitbucket.org/richardbarlow/sr-hw-prod-coord/wiki/Kit_Collation seems useful)
- work out what needs fixing
- determine whether we have enough kit to run with the SR kits or need to build something of our own

**Comment by PeterJCLaw** [comment]
I'm expecting that the above will involve at least a weekend and possibly longer either in Newbury or another location. Either way we'll need to travel for ourselves and possibly transport of the kit back & forth.

Question for the treasurer @prophile: are there any funds available to cover travel costs and/or hiring a van to move the kit/location to work in?

**Comment by andybusse** [comment]
Just received details for container access but been specifically told only to pass to keyholders. Have put "keyholders" in as an item for tomorrow's meeting, but you'd need your own transport to get there.

**Comment by andybusse** [comment]
There's also 16 kits in "UKPostBox" storage, cost to ship somewhere is ~£270

**Comment by PeterJCLaw** [comment]
This is in progress following last weekend's kit collation session, though more work is needed.

**Comment by PeterJCLaw** [comment]
While the kit hasn't all been prepared (or even fixed yet), I'm confident that we understand the status of the kit sufficiently.
