### ISSUE TITLE
Plan for how teams will program the kit (revive the IDE or come up with an alternative)

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#13]

**Comment by PeterJCLaw** [comment]
My assumption here is that we'll use the IDE. Only if we get strong feedback from teachers in the survey which @RealOrangeOne is running that it's not needed do I see us doing anything else.

**Comment by PeterJCLaw** [comment]
The survey showed that some teams (a small number, but unfortunately more than none) would struggle to install things on their school computers and didn't indicate they could work around this by using their own machines.

We therefore need a hosted solution. I think using the IDE provides the best solution at this point, both as something which we know how to deploy and as something we can have good confidence will work for everyone.

I've raised https://github.com/srobo/tasks/issues/16 for investigating a longer-term replacement, but I think that's out of scope for SR2019.

I'm therefore closing this on the expectation that we'll use the IDE.
