### ISSUE TITLE
Recruit volunteers for SR2019

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#15]

**Comment by PeterJCLaw** [comment]
@Adimote is there a useful milestone for this?

**Comment by PeterJCLaw** [comment]
@Adimote is the presence of this task in the system useful? It feels like this is essentially an evergreen task which is just a part of your role, rather than something with a specific outcome. Do you agree?
If so, could we close this?

**Comment by PeterJCLaw** [comment]
The competition has happened, we had volunteers.
