### ISSUE TITLE
Recruit teams for SR2019

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#16]

**Comment by PeterJCLaw** [comment]
@RealOrangeOne does https://github.com/srobo/team-emails/pull/1 cover this?

**Comment by andybusse** [comment]
Not necessarily, this includes possibly recruiting new teams through other channels depending on the response we get from the email. I'd suggest leaving this open until we've got the full complement of teams signed up.

**Comment by RealOrangeOne** [comment]
IIRC the trustees suggested _not_ focusing too much on recruitment for this competition year. We have a lot of teams on the mailing lists, and a limited number of places. But hey, we're posting on social media, so something may come of it

**Comment by RealOrangeOne** [comment]
Recruitment will be done in the form of posting the invite form on social media, and the website. I don't think there's merit to doing full-blown outreach for this competition year.

**Comment by RealOrangeOne** [comment]
As the recruitment window for this competition has closed, we can consider this issue closed too. We didn't do any intentional drives for teams this year, however can and likely will in future.
