### ISSUE TITLE
Create a draft budget

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#18]

**Comment by PeterJCLaw** [comment]
@prophile is there an update on this? We could well need to start purchasing kit parts soon, so it would be useful to know where we're at with regards to the budget.

**Comment by PeterJCLaw** [comment]
@prophile how can we help get this done?

**Comment by PeterJCLaw** [comment]
@Tyler-Ward would you like to do the honours and close this?

**Comment by Tyler-Ward** [comment]
We now have a draft budget, currently awaiting trustee approval
