### ISSUE TITLE
Announcement to registered volunteers welcoming them to SR2019

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#22]
Discussed in https://github.com/srobo/core-team-minutes/blob/master/2018/2018-08-22.md

General mailshot announcing that cogs are in motion for SR2019, and where to go to see what's going on (and help out).
Need to think carefully about what goes into this as the announcement channel should be used sparingly.

- Do we ask feedback (in a Google Form) for who is interested in mentoring, events, development, organisation etc.?
- Do we rekindle the googlegroup (or suitable alternative) separately before this goes out?

**Comment by Adimote** [comment]
email was sent
