### ISSUE TITLE
Announce SR2019 to volunteers

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#28]
Announce competition date and venue, and kickstart details to volunteers.

**Comment by PeterJCLaw** [comment]
@Adimote is there an update on this?

**Comment by Adimote** [comment]
Apologies, I thought this had been done with the original email, will draft something in a bit

**Comment by Adimote** [comment]
This was sent! we couldn't announce the competition date but we could announce the kickstart locations and times.

**Comment by Adimote** [comment]
email: https://github.com/srobo/volunteer-emails/pull/1
