### ISSUE TITLE
Prepare website for SR2019 competition cycle

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#29]
Ideally not long after competition is announced, website needs to have the normal splash page back and a news article or two repeating the competition announcement and containing details for kickstart.

**Comment by PeterJCLaw** [comment]
I think the baseline is probably:
- restore the previous homepage (https://github.com/srobo/website/issues/78)
- add a news article about the competition announcement (https://github.com/srobo/website/issues/80)
- [nice to have] refresh the logo on the website pages (https://github.com/srobo/website/issues/79)

@antoinepetty if you're preparing some text for facebook or other long-form social media it would be great to use the same text on the website, alternatively we could keep the long form on the website and have everything else link to that (I've a slight preference for the latter).

@Adimote @RealOrangeOne similarly if you're writing some words for the announcement emails they're likely a good starting point for this as well (at least in terms of topics if not actual words)

**Comment by PeterJCLaw** [comment]
While we don't have the full Kickstart details live yet, I think this is done - we have an article live and have updated the site to match the new branding colours and logo.

**Comment by PeterJCLaw** [comment]
For clarity: I'm suggesting that the full Kickstart details be handled as a separate issue, rather than letting this one remain in a partially completed state.
