### ISSUE TITLE
Clarify fundraising responsibility with trustees

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#30]
Once competition is announced we'll invite trustees to a core team meeting to clarify fundraising expectations from both trustee and core team point of view - particularly as SR2019 funding is tight this is rather important for the longer term.

**Comment by PeterJCLaw** [comment]
@andybusse is this still relevant?

**Comment by trickeydan** [comment]
I believe it is still relevant, although should probably be transferred to https://github.com/srobo/tasks

Both @mildlyincompetent and I did attempt some fundraising earlier this year, but our efforts were not met with much from the Trustees.

**Comment by PeterJCLaw** [comment]
I believe we have obtained some clarity on fundraising - it is primarily the responsibility of the trustees, though their focus is very much on the large-scale aspects of it.

I'm going to close this as it's not providing any value remaining open. I suggest any further desire for information be direct to the trustees directly, or possibly raised as an issue against the [ops manual](https://github.com/srobo/ops-manual/issues).
