### ISSUE TITLE
Book kickstart venues

### ISSUE THREAD

**Issue by andybusse** [srobo/core-team-minutes#32]
Presently this is London and Southampton, provisionally 10th November. Needs to be confirmed

**Comment by PeterJCLaw** [comment]
I consider London to be booked. I've emailed the core team with some things we need to do related to it, though they're mostly things we'd do anyway.

**Comment by PeterJCLaw** [comment]
@mildlyincompetent has confirmed that Southampton is also booked (https://studentrobotics.slack.com/archives/CDCJ93YMC/p1539544818000100?thread_ts=1539544727.000100&cid=CDCJ93YMC)
