### ISSUE TITLE
Upgrade the SR software stack to Python 3

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#34]
This is something that we _should_ do, however it needs investigation into whether it is possible to achieve. If it looks unlikely then in the interests of delivering a stable kit we should not rush this.

**Comment by RealOrangeOne** [comment]
I would argue this should *not* be done this competition cycle. We shouldn't upgrade half way through a competition cycle, for obvious reasons, and I don't think it's a worthwhile thing to spend our time on to complete before kickstart

**Comment by anowlcalledjosh** [comment]
I looked into this a bit last year (in the context of the Hills Road competition). IIRC, libkoki would need to be updated to work with OpenCV 3 (it currently uses OpenCV 2), which looked like a nontrivial task, though I'm no C programmer.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I completely agree that we wouldn't want to change this after Kickstart, though I had been hoping we'd be able to get it done before that (which felt reasonable).

Thanks for the info @anowlcalledjosh.
Just so I understand it a bit better -- can you explain why we'd also need to upgrade OpenCV versions to change Python versions? Do we end up using OpenCV from Python somewhere in a manner which couples us to a particular version? (I'm guessing there's something like OpenCV 2 not being packaged for Python 3 as well?)

If we are indeed coupled to OpenCV 2, then I agree that this is too big for this year.

**Comment by trickeydan** [comment]
Upgrading to Python 3 is too much of a large task and is not a priority.

**Comment by anowlcalledjosh** [comment]
@PeterJCLaw I don't remember the details that well I'm afraid. If you didn't use OpenCV from Python anywhere, then it may well be that you could continue to use OpenCV 2 with Python 3, but it looks like pykoki does use `cv2` (specifically, `cv2.cv.iplimage`, which is ["mega deprecated in 3.0"](https://stackoverflow.com/questions/29339948/convert-mat-to-ipl-image-in-opencv-3-0#comment46867334_29339948)), so OpenCV's extension module for Python is required, and OpenCV 2 doesn't support Python 3 IIRC.

**Comment by PeterJCLaw** [comment]
Since we're not going to do this for this year, I'm closing this.
