### ISSUE TITLE
Decide whether we want a forum

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#36]
We need to decide whether we want to host a forum for teams for the SR2019 cycle.

If we do, then we need to decide whether we self-host or not.
If the latter we need to work out how (and if) we want to identify competitors vs team leaders and who is in which team.

**Comment by antoinepetty** [comment]
I see a lot of benefit in providing a way for teams to communicate with each other for discussing ways to complete the task and having input on troubleshooting anything to do with their bot.

I would be happy with self-hosting but I know Andy Busse has had concerns regarding GDPR when storing information about competitors (who will be under 18).

**Comment by RealOrangeOne** [comment]
If we decide to run it, we need to be _very_ careful with it. If we can host it somewhere else, we should! On the off chance we can find a provider which expose LDAP/SAML, so much the better, but that's unlikely. If not, then we host the LDAP/SAML component.

**Comment by PeterJCLaw** [comment]
As I understand it, the quandaries around self-hosting are mostly about that meaning we need to self-host the accounts. If we're having to be responsible for the accounts anyway, I don't think there's much disadvantage to self-hosting the forum.

**Comment by PeterJCLaw** [comment]
Discussed in [meeting 2018-10-30](https://github.com/srobo/core-team-minutes/blob/master/2018/2018-10-30.md), we do want a forum, we're happy to use a setup similar to that of previous years as long as we're on a recent OS (which we can be fairly sure is secure; i.e: not `saffron`).
