### ISSUE TITLE
Create a survey for teachers from the SR assumption list

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#4]
Assumption list: https://docs.google.com/document/d/1TUWtD6siLcqFc1XXdW9nq0dqFxa7L39hwakIA28F1PM/edit

From https://github.com/srobo/core-team-minutes/blob/master/2018/2018-08-14.md#action-points

**Comment by RealOrangeOne** [comment]
Survey has now been created and is open for review.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne didn't this ship?

**Comment by RealOrangeOne** [comment]
It did.
