### ISSUE TITLE
[Kickstart] Prepare the Game presentation

### ISSUE THREAD

**Issue by Adimote** [srobo/core-team-minutes#44]
We need to announce the game in a super flashy way.

Also please note this presentation will be given by 2 different people, so the creator needs to brief the other venue.

A few similar presentations to look at:
- [SourceBots 2018](https://sourcebots.github.io/sb2018-game-presentation/)
- [SR2017 southampton](https://docs.google.com/presentation/d/1eZveEF-YzN1nAycJsirAKppqrJwpzfpSigcTnt0R_TM/edit#slide=id.g17a8ba71bc_1_182)  (scroll to game section)

**Comment by RealOrangeOne** [comment]
Depends on #14

**Comment by Adimote** [comment]
This has been moved to the https://github.com/srobo/tasks/ repo! see: https://github.com/srobo/tasks/issues/10
