### ISSUE TITLE
[Kickstart] Decide on the Awards we will give out

### ISSUE THREAD

**Issue by Adimote** [srobo/core-team-minutes#45]
We need to announce what the awards will be for the competition, so the teams know what they're working towards.

IIRC we usually have:
- 1st place
- 2nd place
- 3rd place
- Trustees award (Core Team award?)
- Robot and Team Image
- Online presence
- Rookie award
- First Robot Movement (rookies only)

**Comment by anowlcalledjosh** [comment]
In the [2017 competition](https://studentrobotics.org/docs/resources/2017/rulebook.pdf), there was also a rookie award and a "first robot movement" award.

**Comment by Adimote** [comment]
Thanks Josh, have added them!

**Comment by Adimote** [comment]
This has been moved to the https://github.com/srobo/tasks/ repo! see: https://github.com/srobo/tasks/issues/9
