### ISSUE TITLE
[southampton] Inventorize the cupboard

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#6]
From: https://github.com/srobo/core-team-minutes/blob/master/2018/2018-08-08.md#action-points

**Comment by trickeydan** [comment]
Surely this should be identical to the old SR inventory? However I agree that we need to check.

Access to the SR inventory would be useful

**Comment by PeterJCLaw** [comment]
@trickeydan the inventory is at https://github.com/srobo/inventory, though I think that https://www.studentrobotics.org/cgit/inventory.git may be more up to date.

My understanding of this action was that it was to check that the inventory of what was in the cupboard was correct.

If there are discrepancies, I suggest forking https://github.com/PeterJCLaw/inventory (which is up to date) and putting any changes in your fork. Once we have push access to https://github.com/srobo/inventory we can then sync things up.

**Comment by PeterJCLaw** [comment]
Update: core-team members should have push access to https://github.com/srobo/inventory; I've synced it with the others.

**Comment by PeterJCLaw** [comment]
This happened at the first kit checkin session.
