### ISSUE TITLE
Get social media account access

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#7]
Need to contact @jimmythompson to get the credentials to our social media accounts so that we can start using them.

From: https://github.com/srobo/core-team-minutes/blob/master/2018/2018-08-08.md#action-points

**Comment by antoinepetty** [comment]
Current Status: I'm in contact with Jimmy about gaining access to the Facebook and Twitter accounts.

**Comment by antoinepetty** [comment]
I have access to Twitter and Facebook. I will follow up about LinkedIn but that is not a priority as I don't believe we have posted there before.

**Comment by jimmythompson** [comment]
@antoinepetty You are now an admin on Linkedin also.

**Comment by trickeydan** [comment]
@antoinepetty Do you have access to this? https://www.youtube.com/channel/UCq6VuMD5SCS74jtAlmNemRw

If so, it's probably worth updating the branding

**Comment by antoinepetty** [comment]
@trickeydan I will contact Jimmy to gain access.
