### ISSUE TITLE
Match up potential mentors with schools

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#75]
From https://github.com/srobo/core-team-minutes/blob/master/2018/2019-02-06.md#specific

**Comment by Adimote** [comment]
I've sent a wave of emails out to mentors who are within range of teams, gathering their availability. Next step is to allocate them based on their responses.

**Comment by PeterJCLaw** [comment]
The competition has happened, this is no longer relevant.
