### ISSUE TITLE
Email the trustees and get their input on media consent

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/core-team-minutes#77]
From https://github.com/srobo/core-team-minutes/blob/master/2018/2019-02-06.md#specific

**Comment by RealOrangeOne** [comment]
The email has been sent. Diane was going to contact the ICO for guidance. I'll chase this up tomorrow

**Comment by PeterJCLaw** [comment]
@RealOrangeOne from the activity on https://github.com/srobo/tasks/issues/187 it looks like this is done?

**Comment by RealOrangeOne** [comment]
Correct.
